
language: node_js

cache:
  directories:
    - "node_modules"

node_js:
- "8"
- "9"
- "10"
before_install:
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm run test
deploy:
  - provider: script
    # Have to use `&&` because of issue https://github.com/travis-ci/dpl/issues/673
    script: npm run doc && bash ./bin/deploy-gh-pages.sh
    skip_cleanup: true
    on:
      branch: master
      node_js: "10"


env:
  global:
    - "GH_REF=github.com/BrunnerLivio/nest-terminus.git"
