
language: node_js

cache:
  directories:
    - "node_modules"

stages:
  - test
  - name: deploy
    if: "$TRAVIS_TAG =~ ^v.*$"

jobs:
  include:
    - stage: test
      name: "Test"
      node_js:
      - "8"
      - "9"
      - "10"
      before_install:
        - npm i -g npm@latest
      install:
        - npm install
      script:
        - npm run test
    - stage: deploy
      name: "Deploy Docs"
      node_js: "10"
      before_install:
        - npm i -g npm@latest
      install:
        - npm install
      script:
        - echo "Deploying to gh-pages..."
        - npm run doc
        - bash ./bin/deploy-gh-pages.sh
      skip_cleanup: true

env:
  global:
    - "GH_REF=github.com/BrunnerLivio/nest-terminus.git"
