
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm run test
  - npm run doc
  - bash ./bin/deploy-gh-pages.sh
env:
  global:
    - GH_REF: "github.com/BrunnerLivio/nest-terminus.git"
