packages:
  - 'sample/**'

catalog:
  "@commitlint/cli": "19.7.1"
  "@commitlint/config-angular": "19.7.1"
  "@grpc/grpc-js": "1.12.6"
  "@grpc/proto-loader": "0.7.13"
  "@mikro-orm/core": "6.4.5"
  "@mikro-orm/mongodb": "6.4.5"
  "@mikro-orm/mysql": "6.4.5"
  "@mikro-orm/nestjs": "6.1.1"
  "@nestjs/axios": "4.0.0"
  "@nestjs/cli": "^11.0.2"
  "@nestjs/common": "11.0.11"
  "@nestjs/core": "11.0.11"
  "@nestjs/microservices": "11.0.11"
  "@nestjs/mongoose": "11.0.1"
  "@nestjs/platform-express": "11.0.11"
  "@nestjs/platform-fastify": "11.0.11"
  "@nestjs/sequelize": "11.0.0"
  "@nestjs/swagger": "11.0.6"
  "@nestjs/testing": "11.0.11"
  "@nestjs/typeorm": "11.0.0"
  "@prisma/client": "6.3.1"
  "@release-it/conventional-changelog": "10.0.0"
  "@types/express": "5.0.0"
  "@types/jest": "29.5.14"
  "@types/node": "22.13.10"
  "@types/supertest": "6.0.2"
  "@typescript-eslint/eslint-plugin": "6.21.0"
  "@typescript-eslint/parser": "6.21.0"
  "amqp-connection-manager": "4.1.14"
  "amqplib": "0.10.7"
  "axios": "^1.7.9"
  "cli-color": "2.0.4"
  "eslint": "8.57.1"
  "eslint-config-prettier": "10.0.1"
  "eslint-import-resolver-typescript": "^3.6.0"
  "eslint-plugin-deprecation": "^3.0.0"
  "eslint-plugin-import": "^2.27.5"
  "eslint-plugin-jest": "^28.0.0"
  "eslint-plugin-unused-imports": "^4.0.0"
  "fastify": "5.7.3"
  "husky": "9.1.7"
  "ioredis": "5.4.2"
  "jest": "29.7.0"
  "kafkajs": "^2.2.4"
  "lint-staged": "15.4.3"
  "mongoose": "8.10.1"
  "mysql2": "3.12.0"
  "nats": "2.29.2"
  "portfinder": "1.0.35"
  "prettier": "3.5.3"
  "prisma": "6.3.1"
  "reflect-metadata": "0.2.2"
  "release-it": "18.1.2"
  "rollup": "4.34.8"
  "rollup-plugin-dts": "6.1.1"
  "sequelize": "6.37.5"
  "sequelize-typescript": "2.1.6"
  "supertest": "7.0.0"
  "ts-jest": "29.2.6"
  "ts-node": "10.9.2"
  "typeorm": "0.3.22"
  "typescript": "5.7.3"
  "wait-port": "1.1.0"
  "rxjs": "7.8.2"
  "nodemon": "3.1.10"
  "ts-loader": "9.5.4"
  "tsconfig-paths": "4.2.0"
  "class-transformer": "0.5.1"
  "class-validator": "0.14.2"
  "lodash": "4.17.23"
  "concurrently": "9.2.1"
  "redis": "5.8.2"
  "mysql": "2.18.1"
  "@types/sequelize": "6.12.0"
  "eslint-plugin-prettier": "5.2.3"
  "source-map-support": "0.5.21"
